### ISSUE TITLE
Less of an issue... more of a how can I... 

### ISSUE THREAD

**Issue by jacksnodgrass** [paolobarbolini/do-firewall-updater#1]
Is there an official DigitialOcean Firewall API doc? 

Instead of whitelisting an IP, I would like to be able to blacklist an ip and remove a blacklisted ip. 

Is that documented anywhere? 

- jack

**Comment by paolobarbolini** [comment]
They do have [firewall api documentation](https://developers.digitalocean.com/documentation/v2/#firewalls), but they don't support blacklisting ips.
If you have to blacklist bots or things like that from your website I suggest using Cloudflare, which has both whitelist and blacklist capabilities.

**Comment by jacksnodgrass** [comment]
Ok, thanks. I don't think I need cloudflare level stuff.. just thought it would be nice to use an api to block a few ip addresses. I can use firewall-cmd with linux but was hoping to offload that to DO. 

Thanks for the info. 

- jackl
